# Generated by Django 3.2.12 on 2022-08-25 05:11

import cvat.apps.engine.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0050_auto_20220211_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='box_size',
            field=models.CharField(choices=[('none', 'NONE'), ('small', 'SMALL'), ('medium', 'MEDIUM')],
            default='none', max_length=10),
        ),
    ]
