# Generated by Django 3.2.15 on 2022-10-02 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0051_project_box_size'),
        ('engine', '0060_alter_label_parent'),
    ]

    operations = [
    ]
