# Generated by Django 3.2.15 on 2022-10-11 02:55

import cvat.apps.engine.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('engine', '0061_merge_0051_project_box_size_0060_alter_label_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='assignee',
        ),
        migrations.AddField(
            model_name='job',
            name='checker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_checker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='job',
            name='worker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='job_worker', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='box_size',
            field=models.CharField(default='none', max_length=12),
        ),
    ]
