# Generated by Django 3.2.15 on 2022-12-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0062_auto_20221011_0255'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='saved_date',
            field=models.DateTimeField(null=True),
        ),
    ]
