# Generated by Django 3.2.15 on 2022-12-15 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0063_job_saved_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='updated_date',
            field=models.DateTimeField(null=True),
        ),
    ]
