# Generated by Django 3.2.16 on 2023-03-06 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0067_delete_jobcommit'),
    ]

    operations = [
        migrations.CreateModel(
            name='GuideFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.CharField(max_length=1024)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='engine.project')),
            ],
            options={
                'default_permissions': (),
            },
        ),
    ]
