# Generated by Django 3.2.16 on 2023-06-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0068_guidefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='etc',
            field=models.BooleanField(default=False),
        ),
    ]
