# Generated by Django 4.2.1 on 2024-03-04 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0070_auto_20231117_0517"),
    ]

    operations = [
        migrations.AddField(
            model_name="labeledshape",
            name="encoding",
            field=models.BinaryField(default=None, null=True),
        ),
    ]
