# Generated by Django 4.2.1 on 2024-03-07 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("engine", "0071_labeledshape_encoding"),
    ]

    operations = [
        migrations.CreateModel(
            name="Umap",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tx", models.BinaryField()),
                ("ty", models.BinaryField()),
                ("annotations", models.TextField()),
                ("result_image", models.TextField()),
                ("created_date", models.DateTimeField(auto_now_add=True)),
                (
                    "label",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="engine.label"
                    ),
                ),
            ],
            options={
                "default_permissions": (),
                "unique_together": {("label",)},
            },
        ),
    ]
